### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by coffeverton** [raulsaavedr/firefox_update#1]
I cloned the repository, and tried to run the script_firefox file, but it does nothing.

I changed the permissions, with chmod +x, but still no luck.

**Comment by raulsaavedr** [comment]
Well just type ./check_firefox and the script will do everthing. Also you can view the commands above and excute the commands manually . Let me know if doesn't work.

**Comment by coffeverton** [comment]
Like this?

```
everton@everton:~/Programas/firefox_update$ ./check_firefox
bash: ./check_firefox: No such file or directory
```
When I type just `./script_firefox`, then nothing is returned.
I'm on Debian 9.

**Comment by raulsaavedr** [comment]
ok verify the filename of the file is check_firefox and not script_firefox.

2018-06-14 8:17 GMT-04:00 Everton Pereira <notifications@github.com>:
